import type { SimpleIcon } from 'simple-icons';
import {
  siDotnet,
  siSharp,
  siGraphql,
  siRabbitmq,
  siAngular,
  siReact,
  siReactivex,
  siTypescript,
  siSass,
  siDocker,
  siKubernetes,
  siJenkins,
  siRailway,
  siPostgresql,
  siRedis,
  siMongodb,
  siGit,
  siJira,
  siRider,
  siPostman,
  siSwagger,
  siSonarqubeserver,
  siNuget,
  siAnthropic,
  siGithubcopilot,
} from 'simple-icons';

const iconMap: Record<string, SimpleIcon> = {
  '.NET 8':               siDotnet,
  'C#':                   siSharp,
  'GraphQL':              siGraphql,
  'RabbitMQ':             siRabbitmq,
  'Angular':              siAngular,
  'React':                siReact,
  'React Native':         siReact,
  'RxJS':                 siReactivex,
  'TypeScript':           siTypescript,
  'SCSS':                 siSass,
  'Docker':               siDocker,
  'Kubernetes':           siKubernetes,
  'Jenkins':              siJenkins,
  'Railway':              siRailway,
  'PostgreSQL':           siPostgresql,
  'Redis':                siRedis,
  'MongoDB':              siMongodb,
  'Git':                  siGit,
  'Jira':                 siJira,
  'Rider':                siRider,
  'Postman':              siPostman,
  'Swagger':              siSwagger,
  'SonarQube':            siSonarqubeserver,
  'NuGet':                siNuget,
  'Claude':               siAnthropic,
  'GitHub Copilot':       siGithubcopilot,
};

export function getIcon(name: string): SimpleIcon | null {
  return iconMap[name] ?? null;
}
